import React from 'react';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Spacetime',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  // eslint-disable-next-line prettier/prettier
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
